### PR TITLE
Added Minimal Working Example for a docker container

### PR DESCRIPTION
**Pull request by helt**
This PR adds an example of how to create a RESTful web service of nl4dv with fastapi which is wrapped in a docker image.

* VERY minimal example. No error handling, no parameterization such as file selection etc.
* works for me (TM)
* added the example into an arbitrary directory. Maybe some other place would be better
* uses `nl4dv` pip package, not the source distribution.

### CODE REVIEW

**Comment by helt** [comment]
* VERY minimal example. No error handling, no parameterization such as file selection etc.
* works for me (TM)
* added the example into an arbitrary directory. Maybe some other place would be better

**Comment by arpitnarechania** [comment]
Thanks, @helt, for your PR. Supporting a (docker) containerized version of NL4DV will be very helpful. I followed your documentation and it all works exactly as mentioned. 👍 

However, as you mentioned, we need to support parameterization, such as setting the dataset, dependency parser, and so on. I have already started making these changes in a local branch (checked out from your fork). 

**Should I push related changes to your fork (I might require write privileges) OR create a new branch within the base nl4dv repository?**

**Comment by helt** [comment]
Tell me what I need to change in order to make this PR mergable and lll happily commit. Alternatively, just continue on your branch and close this PR.

**Comment by arpitnarechania** [comment]
I need to speak with my team if we should have separate repositories in the organization like `nl4dv-docker`, `nl4dv-examples` to keep the source minimal.  So, to stop bothering you while we figure out what's best, I am closing this PR and will keep working on the local branch.

I will obviously attribute the eventual PR to you :).

**Comment by arpitnarechania** [comment]
Hey @helt, just wanted to update you that we have a docker image [_**arpitnarechania/nl4dv**_](https://hub.docker.com/r/arpitnarechania/nl4dv) that is also open-sourced and available in a new repository: [**_nl4dv-docker_**](https://github.com/nl4dv/nl4dv-docker).

Thank you for the idea as well as your initial contribution. I have retained FastAPI+Gunicorn for the web application but changed the base image in the Dockerfile to ubuntu (to add Java for CoreNLP, etc).

Do check it out!

**Pull request closed without merging**
